import { initializeApp } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js";
import { getAuth, GoogleAuthProvider, onAuthStateChanged, signInWithPopup, signOut } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-auth.js";
import { getFirestore, collection, doc, getDoc, getDocs, setDoc, addDoc, updateDoc, query, where, orderBy, limit, onSnapshot, serverTimestamp } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";

const fb = initializeApp(firebaseConfig), auth = getAuth(fb), db = getFirestore(fb);
const provider = new GoogleAuthProvider(); provider.setCustomParameters({prompt:"select_account"});
const root = document.querySelector("#app");
let user, me, view="dashboard", records=[], requests=[], messages=[], people=[], unsubs=[];
let pendingTag = new URLSearchParams(location.search).get("tag");

const twDate=()=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Taipei"}).format(new Date());
const fmt=v=>v?.toDate?new Intl.DateTimeFormat("zh-TW",{dateStyle:"short",timeStyle:"short",timeZone:"Asia/Taipei"}).format(v.toDate()):"—";
const tm=v=>v?.toDate?new Intl.DateTimeFormat("zh-TW",{hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Asia/Taipei"}).format(v.toDate()):"—";
const e=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const badge=s=>`<span class="badge ${["啟用","已核准","已簽退"].includes(s)?"good":["待核准","待審核","已簽到"].includes(s)?"warn":"neutral"}">${e(s)}</span>`;
function toast(s){const x=document.querySelector("#toast");x.textContent=s;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2400)}
function loading(s="正在連接安全後臺…"){root.innerHTML=`<main class="loading-page"><div class="loading-card"><div class="spinner"></div><h1>${e(s)}</h1><p>臺北市立大學運動能力分析實驗室</p></div></main>`}

function loginPage(note="請使用已登記的個人 Google 帳號登入。登入一次後，日常掃描 NFC Tag 不必再次輸入密碼。"){
 root.innerHTML=`<main class="login-page"><section class="login-brand"><div class="brand-mark">SPA</div><h1>實驗室<br>智慧出勤</h1><p>以個人帳號、現場 NFC Tag 與雲端時間建立可追溯的出勤紀錄。</p><div class="privacy-note"><span>⌾</span><span>不蒐集手機 IMEI、序號或 MAC，也不持續追蹤位置。</span></div></section><section class="login-panel"><div class="env-chip">正式後臺・Spark 免費方案</div><h2>歡迎使用</h2><p>${e(note)}</p><button class="google-login" id="login"><span class="google-g">G</span><span><strong>使用 Google 帳號登入</strong><small>系統以帳號確認打卡者身分</small></span><span>›</span></button><div class="demo-disclaimer"><strong>首次登入</strong><br>系統會建立待核准帳號；管理者確認身分後才開通打卡。</div></section></main>`;
 document.querySelector("#login").onclick=async()=>{try{await signInWithPopup(auth,provider)}catch(err){loginPage(err.code==="auth/popup-closed-by-user"?"登入視窗已關閉，尚未登入。":"登入未完成，請稍後再試。")}};
}
async function profile(u){const r=doc(db,"users",u.uid),s=await getDoc(r);if(!s.exists()){const p={uid:u.uid,email:u.email,name:u.displayName||u.email,role:"pending",active:false,createdAt:serverTimestamp(),lastLoginAt:serverTimestamp()};await setDoc(r,p);return p}await updateDoc(r,{lastLoginAt:serverTimestamp(),name:u.displayName||s.data().name});return{id:s.id,...s.data()}}
function pending(){root.innerHTML=`<main class="punch-screen"><section class="punch-card"><div class="success-ring pending-ring">⌛</div><h1>帳號等待核准</h1><p>Google 帳號已確認，管理者尚未開通打卡權限。</p><div class="receipt"><div><span>姓名</span><strong>${e(me.name)}</strong></div><div><span>帳號</span><strong>${e(me.email)}</strong></div><div><span>狀態</span><strong>待管理者核准</strong></div></div><button class="secondary-btn full" onclick="location.reload()">重新檢查</button><button class="link-plain" id="logout">改用其他帳號</button></section></main>`;document.querySelector("#logout").onclick=()=>signOut(auth)}
function err(){toast("部分雲端資料暫時無法讀取")}
function watch(){unsubs.forEach(f=>f());unsubs=[];const admin=me.role==="admin";
 const rq=(name)=>admin?query(collection(db,name),orderBy(name==="attendance"?"date":"createdAt","desc"),limit(200)):query(collection(db,name),where(name==="messages"?"toUid":"userId","==",user.uid),limit(100));
 const sorted=(snap,name)=>snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>name==="attendance"?String(b.date).localeCompare(String(a.date)):(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0));
 unsubs.push(onSnapshot(rq("attendance"),s=>{records=sorted(s,"attendance");if(!pendingTag)render()},err));
 unsubs.push(onSnapshot(rq("requests"),s=>{requests=sorted(s,"requests");if(!pendingTag)render()},err));
 unsubs.push(onSnapshot(rq("messages"),s=>{messages=sorted(s,"messages");if(!pendingTag)render()},err));
 if(admin)unsubs.push(onSnapshot(query(collection(db,"users"),orderBy("createdAt","desc")),s=>{people=s.docs.map(d=>({id:d.id,...d.data()}));if(!pendingTag)render()},err));
}
async function punch(id){loading("正在驗證 NFC Tag 與身分…");try{const ts=await getDoc(doc(db,"tags",id));if(!ts.exists()||!ts.data().active)return punchError("無法驗證這張 Tag","請使用實驗室核發且已啟用的 NFC Tag。");const t=ts.data(),rid=`${user.uid}_${twDate()}`,r=doc(db,"attendance",rid),old=await getDoc(r),field=t.action==="checkin"?"checkInAt":"checkOutAt";if(old.exists()&&old.data()[field])return punchOK(t.action,old.data()[field],t.placeName,true);if(t.action==="checkout"&&!old.exists())return punchError("今天尚未簽到","請先完成簽到，再掃描簽退 Tag。");if(t.action==="checkin")await setDoc(r,{userId:user.uid,name:me.name,date:twDate(),checkInAt:serverTimestamp(),checkOutAt:null,checkInTagId:id,checkOutTagId:null,placeId:t.placeId,placeName:t.placeName,status:"已簽到",source:"NFC",createdAt:serverTimestamp(),updatedAt:serverTimestamp()});else await updateDoc(r,{checkOutAt:serverTimestamp(),checkOutTagId:id,status:"已簽退",updatedAt:serverTimestamp()});const fresh=await getDoc(r);punchOK(t.action,fresh.data()[field],t.placeName,false)}catch(x){console.error(x);punchError("打卡未完成","網路或權限驗證失敗，系統沒有建立紀錄。")}}
function punchOK(a,t,p,dupe){const n=a==="checkin"?"簽到":"簽退";root.innerHTML=`<main class="punch-screen"><section class="punch-card"><div class="success-ring">✓</div><h1>${dupe?`已完成${n}`:`${n}成功`}</h1><p>${dupe?"既有紀錄已確認，沒有重複新增。":"雲端系統已接收，您可以放心離開。"}</p><div class="receipt"><div><span>人員</span><strong>${e(me.name)}</strong></div><div><span>時間</span><strong>${e(fmt(t))}</strong></div><div><span>地點</span><strong>${e(p)}</strong></div><div><span>驗證</span><strong>帳號與 NFC Tag 已通過</strong></div></div><button class="primary-btn full" id="home">查看我的紀錄</button></section></main>`;if(navigator.vibrate)navigator.vibrate([80,40,80]);document.querySelector("#home").onclick=home}
function punchError(a,b){root.innerHTML=`<main class="punch-screen"><section class="punch-card"><div class="success-ring error-ring">!</div><h1>${e(a)}</h1><p>${e(b)}</p><button class="secondary-btn full" id="home">返回系統</button></section></main>`;document.querySelector("#home").onclick=home}
function home(){pendingTag=null;history.replaceState({},"",location.pathname);render()}

const nav=()=>me.role==="admin"?[["dashboard","⌂","總覽"],["attendance","◫","出勤紀錄"],["exceptions","!","異常與申請"],["messages","✉","訊息中心"],["people","♙","人員與 Tag"]]:[["dashboard","⌂","我的首頁"],["attendance","◫","打卡紀錄"],["requests","＋","請假／補登"],["messages","✉","訊息"]];
function render(){if(!me?.active||!["staff","admin"].includes(me.role))return pending();const n=nav(),title=n.find(x=>x[0]===view)?.[2];root.innerHTML=`<div class="shell"><aside class="sidebar"><div class="side-brand"><div class="brand-mark">SPA</div><div><strong>運動能力分析<br>實驗室</strong><small>智慧出勤系統</small></div></div><nav class="nav">${n.map(x=>`<button data-view="${x[0]}" class="${view===x[0]?"active":""}"><span class="icon">${x[1]}</span>${x[2]}</button>`).join("")}</nav><div class="side-bottom"><div class="user-mini"><span class="avatar sm">${e(me.name[0])}</span><div><strong>${e(me.name)}</strong><small>${me.role==="admin"?"系統總管":"同仁"}</small></div></div><button class="logout" id="logout">登出</button></div></aside><main class="main"><header class="topbar"><div><h1>${e(title)}</h1><p>臺北市立大學運動能力分析實驗室</p></div><div class="top-actions"><span class="chip hide-mobile">正式雲端後臺</span><span class="chip">${e(me.name)}</span></div></header><div class="content">${page()}</div></main><nav class="mobile-bar">${n.slice(0,4).map(x=>`<button data-view="${x[0]}" class="${view===x[0]?"active":""}"><span>${x[1]}</span>${x[2]}</button>`).join("")}</nav></div>`;bind()}
function page(){if(view==="dashboard")return me.role==="admin"?adminDash():staffDash();if(view==="attendance")return `<div class="page-title"><div><h2>${me.role==="admin"?"全體":"我的"}出勤紀錄</h2><p>手機時間不作為正式時間。</p></div><button class="secondary-btn" id="export">匯出 CSV</button></div><div class="card">${table(records)}</div>`;if(view==="requests")return requestPage();if(view==="exceptions")return exceptionPage();if(view==="messages")return messagePage();if(view==="people")return peoplePage();return""}
const stat=(a,b,c,d)=>`<div class="stat"><div class="stat-top"><span>${e(a)}</span><span class="stat-icon">${c}</span></div><strong>${e(b)}</strong><small>${e(d)}</small></div>`;
function adminDash(){const r=records.filter(x=>x.date===twDate()),p=people.filter(x=>!x.active).length;return `<section class="hero-card"><div><h2>今日出勤概況</h2><p>雲端紀錄會即時同步。</p></div><div class="clock"><strong>${new Date().toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit"})}</strong><small>${twDate()}</small></div></section><section class="stats">${stat("已簽到",r.length,"✓","今日紀錄")}${stat("已簽退",r.filter(x=>x.checkOutAt).length,"◷","今日完成")}${stat("待審申請",requests.filter(x=>x.status==="待審核").length,"!","需要處理")}${stat("待核准帳號",p,"♙","確認身分")}</section><div class="card"><div class="card-head"><h3>今日人員狀況</h3></div>${table(r)}</div>`}
function staffDash(){const r=records.find(x=>x.date===twDate());return `<section class="hero-card"><div><h2>${r?.checkInAt?"今天已完成簽到":"今天尚未簽到"}</h2><p>${r?.checkInAt?`${e(r.placeName)}・${tm(r.checkInAt)}`:"請至指定工作地點掃描 NFC Tag。"}</p></div><div class="clock"><strong>${new Date().toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit"})}</strong><small>${twDate()}</small></div></section><section class="stats">${stat("本月紀錄",records.filter(x=>x.date?.startsWith(twDate().slice(0,7))).length,"✓","已同步")}${stat("今日簽到",tm(r?.checkInAt),"◷","雲端時間")}${stat("今日簽退",tm(r?.checkOutAt),"↗","雲端時間")}${stat("未讀訊息",messages.filter(x=>!x.read).length,"✉","管理者訊息")}</section><div class="card"><div class="card-head"><h3>最近打卡紀錄</h3></div>${table(records.slice(0,5))}</div>`}
function table(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>人員</th><th>日期</th><th>簽到</th><th>簽退</th><th>地點</th><th>狀態</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${e(r.name)}</td><td>${e(r.date)}</td><td>${tm(r.checkInAt)}</td><td>${tm(r.checkOutAt)}</td><td>${e(r.placeName)}</td><td>${badge(r.status)}</td></tr>`).join("")}</tbody></table></div>`:`<div class="empty">目前沒有紀錄</div>`}
function requestPage(){return `<div class="page-title"><div><h2>請假與補登</h2><p>原始紀錄不直接修改。</p></div></div><div class="grid-2"><div class="card"><div class="card-head"><h3>提出新申請</h3></div><form class="card-body" id="req"><div class="form-grid"><div class="field"><label>類型</label><select name="type"><option>補登</option><option>請假</option><option>公出</option><option>紀錄更正</option></select></div><div class="field"><label>日期</label><input name="date" type="date" required value="${twDate()}"></div></div><div class="field field-gap"><label>原因</label><textarea name="reason" required maxlength="500"></textarea></div><div class="form-actions"><button class="primary-btn">送出</button></div></form></div><div class="card"><div class="card-head"><h3>申請紀錄</h3></div><div class="card-body">${requests.map(x=>`<div class="message"><div class="message-head"><strong>${e(x.type)}・${e(x.date)}</strong>${badge(x.status)}</div><p>${e(x.reason)}</p></div>`).join("")||'<div class="empty">尚無申請</div>'}</div></div></div>`}
function exceptionPage(){return `<div class="page-title"><div><h2>異常與申請</h2><p>先聯繫、再確認。</p></div></div><div class="card"><div class="table-wrap"><table><thead><tr><th>人員</th><th>事項</th><th>日期</th><th>說明</th><th>狀態</th><th>處理</th></tr></thead><tbody>${requests.map(x=>`<tr><td>${e(x.name)}</td><td>${e(x.type)}</td><td>${e(x.date)}</td><td>${e(x.reason)}</td><td>${badge(x.status)}</td><td>${x.status==="待審核"?`<button class="link-btn review" data-id="${x.id}" data-status="已核准">核准</button> <button class="link-btn review" data-id="${x.id}" data-status="退回">退回</button>`:"—"}</td></tr>`).join("")}</tbody></table></div></div>`}
function messagePage(){return `<div class="page-title"><div><h2>訊息中心</h2><p>出勤提醒與關懷紀錄。</p></div></div><div class="card"><div class="card-body">${messages.map(x=>`<article class="message ${x.read?"":"unread"}"><div class="message-head"><strong>${e(x.title)}</strong><time>${fmt(x.createdAt)}</time></div><p>${e(x.body)}</p>${me.role!=="admin"&&!x.read?`<button class="link-btn read" data-id="${x.id}">標記已讀</button>`:""}</article>`).join("")||'<div class="empty">目前沒有訊息</div>'}</div></div>`}
function peoplePage(){return `<div class="page-title"><div><h2>人員與 Tag</h2><p>確認 Google 帳號後開通權限。</p></div></div><div class="grid-2"><div class="card"><div class="table-wrap"><table><thead><tr><th>姓名／帳號</th><th>角色</th><th>狀態</th><th>操作</th></tr></thead><tbody>${people.map(p=>`<tr><td><strong>${e(p.name)}</strong><br><small>${e(p.email)}</small></td><td>${p.role==="admin"?"系統總管":p.role==="staff"?"同仁":"待核准"}</td><td>${badge(p.active?"啟用":"待核准")}</td><td>${p.id===user.uid?"目前帳號":`<button class="link-btn toggle" data-id="${p.id}" data-on="${!p.active}">${p.active?"停用":"核准為同仁"}</button>`}</td></tr>`).join("")}</tbody></table></div></div><div class="card"><div class="card-head"><h3>打卡位置</h3></div><div class="card-body"><p>運動能力分析實驗室</p><p>簽到 Tag：lab-checkin<br>簽退 Tag：lab-checkout</p><p class="fine-print">固定網址可能被轉傳，不能單獨視為絕對位置證明。</p></div></div></div>`}
function bind(){document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.querySelector("#logout").onclick=()=>signOut(auth);document.querySelector("#export")?.addEventListener("click",exportCsv);document.querySelector("#req")?.addEventListener("submit",async ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget);await addDoc(collection(db,"requests"),{userId:user.uid,name:me.name,type:f.get("type"),date:f.get("date"),reason:f.get("reason"),status:"待審核",createdAt:serverTimestamp()});toast("申請已送出")});document.querySelectorAll(".read").forEach(b=>b.onclick=()=>updateDoc(doc(db,"messages",b.dataset.id),{read:true,readAt:serverTimestamp()}));document.querySelectorAll(".review").forEach(b=>b.onclick=()=>updateDoc(doc(db,"requests",b.dataset.id),{status:b.dataset.status,reviewedAt:serverTimestamp(),reviewedBy:user.uid}));document.querySelectorAll(".toggle").forEach(b=>b.onclick=()=>updateDoc(doc(db,"users",b.dataset.id),{active:b.dataset.on==="true",role:b.dataset.on==="true"?"staff":"pending",approvedAt:serverTimestamp(),approvedBy:user.uid}))}
function exportCsv(){const rs=[["人員","日期","簽到","簽退","地點","狀態"],...records.map(r=>[r.name,r.date,tm(r.checkInAt),tm(r.checkOutAt),r.placeName,r.status])],csv="\ufeff"+rs.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`出勤紀錄_${twDate()}.csv`;a.click();URL.revokeObjectURL(a.href)}

loading();onAuthStateChanged(auth,async u=>{unsubs.forEach(f=>f());user=u;if(!u)return loginPage(pendingTag?"請先完成身分驗證，登入後系統會接續處理現場打卡。":undefined);loading("正在確認帳號權限…");try{me=await profile(u);if(!me.active||!["staff","admin"].includes(me.role))return pending();watch();pendingTag?punch(pendingTag):render()}catch(x){console.error(x);punchError("後臺連線失敗","Firebase 尚未完成設定，或目前網路無法連線。")}});
